  const jmbgLength: number = 13

  const regions = new Map([
    ["01", "stranci u BiH"],
    ["02", "stranci u Crnoj Gori"],
    ["03", "stranci u Hrvatskoj"],
    ["04", "stranci u Makedoniji"],
    ["05", "stranci u Sloveniji"],
    ["07", "stranci u Srbiji (bez pokrajina)"],
    ["08", "stranci u Vojvodini"],
    ["09", "stranci na Kosovu i Metohiji"],
    ["10", "Banja Luka"],
    ["11", "Bihać"],
    ["12", "Doboj"],
    ["13", "Goražde"],
    ["14", "Livno"],
    ["15", "Mostar"],
    ["16", "Prijedor"],
    ["17", "Sarajevo"],
    ["18", "Tuzla"],
    ["19", "Zenica"],
    ["21", "Podgorica"],
    ["26", "Nikšić"],
    ["29", "Pljevlja"],
    ["30", "Osijek, Slavonija regija"],
    ["31", "Bjelovar, Virovitica, Koprivnica, Pakrac, Podravina regija"],
    ["32", "Varaždin, Međimurje regija"],
    ["33", "Zagreb"],
    ["34", "Karlovac"],
    ["35", "Gospić, Lika regija"],
    ["36", "Rijeka, Pula, Istra i Primorje regija"],
    ["37", "Sisak, Banovina regija"],
    ["38", "Split, Zadar, Dubrovnik, Dalmacija regija"],
    ["39", "Hrvatska ostalo"],
    ["41", "Bitolj"],
    ["42", "Kumanovo"],
    ["43", "Ohrid"],
    ["44", "Prilep"],
    ["45", "Skoplje"],
    ["46", "Strumica"],
    ["47", "Tetovo"],
    ["48", "Veles"],
    ["49", "Štip"],
    ["50", "Slovenija"],
    ["71", "Beograd regija"],
    ["72", "Šumadija"],
    ["73", "Niš"],
    ["74", "Južna Morava"],
    ["75", "Zaječar"],
    ["76", "Podunavlje"],
    ["77", "Podrinje i Kolubara"],
    ["78", "Kraljevo"],
    ["79", "Užice"],
    ["80", "Novi Sad"],
    ["81", "Sombor"],
    ["82", "Subotica"],
    ["85", "Zrenjanin"],
    ["86", "Pančevo"],
    ["87", "Kikinda"],
    ["88", "Ruma"],
    ["89", "Sremska Mitrovica"],
    ["91", "Priština"],
    ["92", "Kosovska Mitrovica"],
    ["93", "Peć"],
    ["94", "Đakovica"],
    ["95", "Prizren"],
    ["96", "Kosovsko Pomoravski okrug"]
  ]);

  export { jmbgLength, regions }